### ISSUE TITLE
Sprint 1 - Board Design

### ISSUE THREAD

**Issue by ajtran303** [ajtran303/quizzery#8]
- [x] #1 **Prework** [create-react-app tutorial](https://create-react-app.dev/)

- [x] #3 Landing Page / Start Button

- [x] #4 Board Renders when click start

- [x] #5 Board has columns, content

**Comment by ajtran303** [comment]
Let's both do the create-react-app tutorial. I think it's a game! We can do it before we meet again tomorrow afternoon.

**Comment by ajtran303** [comment]
Researching other [JavaScript Jeopardy repositories](https://github.com/search?l=JavaScript&o=desc&q=jeopardy+react&s=stars&type=Repositories)

There is a [Jeopardy API called jService](https://jservice.io/)

If we [install it locally](https://github.com/sottenad/jService), I think that we could be fine by just pulling questions from 1 or 2 seasons of Jeopardy. 

All of the data from the jService api comes from [J! Archive](https://j-archive.com/). According to the archive, the first season of Jeopardy had [191 episodes](https://j-archive.com/showseason.php?season=1). That should definitely be enough data!

**Comment by ajtran303** [comment]
Categories and questions [from the first show](http://www.j-archive.com/showgame.php?game_id=173)
